### ISSUE TITLE
move to JuliaPy org?

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/PythonCall.jl#150]
At some point, it might be worthwhile to move PythonCall.jl and friends to the JuliaPy organization.  (Up to you, of course!)

**Comment by cjdoris** [comment]
I'm happy to consider it. What are the ramifications (e.g. in terms of ownership, who can write, etc.)?

**Comment by stevengj** [comment]
I think it means that any owners of JuliaPy would have write permission, though in practice people tend to ask for permission to merge pull requests into repos maintained by someone else anyway.  (In the long run, this makes routine maintenance easier and adds some security if you get busy with other things.)

**Comment by zsz00** [comment]
If move to JuliaPy, There are pyCall.jl vs PythonCall.jl, Conda.jl vs CondaPkg.jl, pyjulia vs JuliaCall in JuliaPy . 
This will lead to some confusion of choice, but more vigorous competition and co-operation. 
I think it might be a good thing!!

**Comment by cjdoris** [comment]
Self bump (I'm on it).
