### ISSUE TITLE
add pyconvert(x) 

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaPy/PythonCall.jl#172]
For convenience, it would be nice to expose
```julia
pyconvert(x) = pyconvert(Any, x)
```

**Comment by cjdoris** [comment]
Perhaps, but you generally shouldn't be using `pyconvert(Any, x)`, you should use a more specific type. The only good reasons I can see for `pyconvert(Any, x)` are:
- Interactive use, where you already know the conversion will do what you want.
- Generic programming, where you don't actually know anything about `x`.

**Comment by CarloLucibello** [comment]
Those 2 usage examples seem pretty common. Moreover, I would find it very useful to have a `pyconvert(Any, x)` with a recursive behavior, something like what I poorly implemented [https://github.com/CarloLucibello/HuggingFaceDatasets.jl](https://github.com/CarloLucibello/HuggingFaceDatasets.jl/blob/main/src/transforms.jl)

**Comment by cjdoris** [comment]
I've previously had discussions about adding a function `pyconvertnative(x)` which converts `x` (recursively) to a 'native' Julia object if possible (`list` to `Vector`, `dict` to `Dict` etc.).

**Comment by hhaensel** [comment]
I just added my two cents to the `pyconvertnative()` discussion, see #128 

Maybe we could continue the discussion here?
