### ISSUE TITLE
Importing JuliaCall interferes with Ctrl + C behavior in Python console

### ISSUE THREAD

**Issue by Wainberg** [JuliaPy/PythonCall.jl#223]
Normally in the Python console, if you've typed a line but haven't run it yet, pressing Ctrl + C discards what you've typed, displays `KeyboardInterrupt` without a stack trace, and starts a new line. 

After importing JuliaCall, this behavior changes. Pressing Ctrl + C on its own appears to do nothing - you can still type on the current line. But when you press Enter, you get a `KeyboardInterrupt` *with* a stack trace. Everything you've typed between Ctrl + C and Enter may get executed - or it may not.

For example, normally if you type "fo", then press Ctrl + C, then type "o = 1", then press Enter, it discards the "fo" and assigns "o = 1":
```
>>> fo
KeyboardInterrupt
>>> o = 1
>>> o
1
```

After importing JuliaCall, it still assigns o = 1, but looks like this:
```
>>> import juliacall
>>> foo = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>> o
1
```

But if o was already defined, the assignment fails:
```
>>> import juliacall
>>> o = 0
>>> foo = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>> o
0
```

**Comment by cjdoris** [comment]
What version of JuliaCall are you on? I recently changed the signal handling for precisely this reason.

**Comment by Wainberg** [comment]
I'm using the latest version, 0.9.6. My Python is 3.10.6 and Julia is 1.8.0.

**Comment by cjdoris** [comment]
Ok thanks. I'll take a look sometime - signal handling is tricky.

**Comment by Wainberg** [comment]
Still worth a fix :)

**Comment by cjdoris** [comment]
Is it still an issue? It appears to work fine in Julia 0.9.14 on Windows.

(You can make it not fine again by launching Python like `python -X juliacall-handle-signals=yes`.)

**Comment by Wainberg** [comment]
Ah cool, did you fix it since last year? I haven't checked.
