### ISSUE TITLE
CondaPkg opt out doesn't work

### ISSUE THREAD

**Issue by aditya-sengupta** [JuliaPy/PythonCall.jl#301]
**Affects:** PythonCall

**Describe the bug**
Opting out of CondaPkg.jl by setting an environment variable as stated in the documentation doesn't work. 

Steps to reproduce: in a directory with a Python venv, run
```
ENV["JULIA_CONDAPKG_BACKEND"] = "Null"
ENV["JULIA_PYTHONCALL_EXE"] = "./.venv/bin/python"
using PythonCall
pyexec("import sys; print(sys.executable)", Main)
```
Expected output is `/path/to/pwd/.venv/bin/python`, actual output is `/path/to/pwd/.CondaPkg/env/bin/python`.

**Your system**
Please provide detailed information about your system:
- MacOS Ventura 13.2.1 on a 2021 MacBook Pro with Apple M1 Pro chip
- Julia 1.8.5, Python 3.10.10 (desired, in venv) and Python 3.11.3 (undesired, in Conda), PythonCall v0.9.12,
```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 8

(testproject) pkg> status
Project TestProject v0.1.0
Status `~/projects/testproject/Project.toml`
  [15e1cf62] NPZ v0.4.3
  [6099a3de] PythonCall v0.9.12
  [276daf66] SpecialFunctions v2.2.0
  [bc48ee85] Tullio v0.3.5
```

**Additional context**
I'm doing this so I can import a Python library on a local path and keep using modified versions of it, like with `conda develop` or `pip install -e`. I initially got it working by installing in the venv and pyimporting from there, but that doesn't seem to work now. If there's a way to do `conda develop`-style importing from CondaPkg I'd be okay with that too!

**Comment by cjdoris** [comment]
I can't reproduce this issue. My guess is that you already have PythonCall loaded in the Julia session before you run that code. Perhaps you have `using PythonCall` in your `startup.jl`?

**Comment by aditya-sengupta** [comment]
Was going back through my old issues and I also found I couldn't reproduce this - I think you were probably right that I had run something in my Julia session before.
