### ISSUE TITLE
transfer to JuliaPy?

### ISSUE THREAD

**Issue by stevengj** [JuliaPy/PythonCall.jl#310]
Might be worth transferring this and related packages to the JuliaPy org to ensure that it can be maintained indefinitely (without forking).

(I just sent @cjdoris an invite to the JuliaPy org.)

**Comment by cjdoris** [comment]
Hi @stevengj, thanks very much for the invite, which I have accepted.

I am certainly happy to move the PythonCall family of repos over, in principle. I'm just wondering if the JuliaPy org has any code of conduct or similar. Basically, I want to retain creative ownership of the packages for the time being - i.e. any changes to the API should go through me. I assume this is true, just want some assurance first.

(I'm happy for others to take over if I go AWOL for months at a time, or to do crucial hotfixes at any time.)

**Comment by stevengj** [comment]
I don't think there is a formal code of conduct, but like most Julia orgs people don't generally merge PRs without the maintainer's permission (unless there is long inactivity).

**Comment by stevengj** [comment]
Just takes a couple of clicks in the settings of each repo: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account

**Comment by cjdoris** [comment]
Thanks, I've not forgotten, just had less time for OSS in recent months so waiting until I have plenty of time to deal with issues arising from the move.

**Comment by stevengj** [comment]
A move is mostly transparent to users, since github sets up redirects for you.

The main thing beyond the transfer is that you'll want to submit a PR to the general registry (e.g. https://github.com/JuliaRegistries/General/pull/89627), because until you do so you won't be able to register new versions.  Other than that, I've never seen any issues.  (For PythonPlot.jl, there was a lag of several months between my transferring it to JuliaPy and updating the URL at the General registry — no one even noticed, until it came time for me to do a version bump.)

**Comment by BeastyBlacksmith** [comment]
> waiting until I have plenty of time to deal with issues arising from the move.

I'd like to point out, that such a move is becoming more important the less time you have for OSS stuff, such that you can distribute the responsibilities over more shoulders

**Comment by xgdgsc** [comment]
Doc on github about is still pointing to old:
<img width="338" alt="截屏2023-09-16 10 58 16" src="https://github.com/JuliaPy/PythonCall.jl/assets/1189869/79c7a071-8adc-4ee7-a132-b7604677d111">

**Comment by cjdoris** [comment]
Good spot thanks!

**Comment by cjdoris** [comment]
@stevengj could you change the docs link on the PythonCall.jl repo please?

**Comment by stevengj** [comment]
It looks like the docs link is correct now?

You should have permissions to make any changes you want?

**Comment by cjdoris** [comment]
@stevengj No it's still wrong - I'm talking about the link in the repo description. I can't change that (or any settings) presumably because I'm a Member not Owner of the organisation.

**Comment by stevengj** [comment]
I've changed you to Owner privileges in JuliaPy

**Comment by cjdoris** [comment]
Thanks!
