### ISSUE TITLE
Raising python errors from Julia functions

### ISSUE THREAD

**Issue by lassepe** [JuliaPy/PythonCall.jl#357]
Some python package apis require the user the raise specific errors in certain scenarios. For example, [Optuna requires the user to conditionally `TrialPruned()` error](https://optuna.readthedocs.io/en/latest/tutorial/10_key_features/003_efficient_optimization_algorithms.html). In the current implementation of PythonCall, raising such errors from julia functions does not seem to be possible.

```
@pyeval `raise optuna.TrialPruned()`
```

fails with `Python: SyntaxError: invalid syntax`.

It would be handy to have  a function like `pyraise` to throw such errors manually.

**Comment by cjdoris** [comment]
You want `@pyexec` (for executing arbitrary python code) not `@pyeval` (which evaluates a single expression):
```
julia> using PythonCall

julia> @pyeval `raise ValueError("hello")`
ERROR: Python: SyntaxError: invalid syntax (REPL[2]:1, line 1)

julia> @pyexec `raise ValueError("hello")`
ERROR: Python: ValueError: hello
```

**Comment by lassepe** [comment]
Nice, this works like charm! Thank you :)
