### ISSUE TITLE
Google search for documentation gives 404 error.

### ISSUE THREAD

**Issue by LilithHafner** [JuliaPy/PythonCall.jl#362]
<img width="868" alt="Screenshot 2023-09-20 at 7 48 23 AM" src="https://github.com/JuliaPy/PythonCall.jl/assets/60898866/e13c1a41-a156-4df1-854d-5fc94ed7f2a2">
<img width="866" alt="Screenshot 2023-09-20 at 7 48 34 AM" src="https://github.com/JuliaPy/PythonCall.jl/assets/60898866/2f5324b2-6e17-46bd-8634-9c3f16e60dd9">

This is probably due to the repo transfer. That URL should really be redirected.

**Comment by cjdoris** [comment]
Yeah. I thought maybe it would redirect automatically (like it does for the repo itself) but no dice. Any idea how?

**Comment by LilithHafner** [comment]
[This is a way to do it](https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7), but it seems really icky to me. It also seems like the best way (a 301 redirect) is [not possible](https://github.com/orgs/community/discussions/22407#discussioncomment-3236600). I suppose this is a disadvantage of pointing to a domain name you do not control.

**Comment by LilithHafner** [comment]
Whelp, here's a fix. It's real icky, but it should work.

As a test,

https://lilithhafner.github.io/PythonCall.jl
https://lilithhafner.github.io/PythonCall.jl/stable/
https://lilithhafner.github.io/PythonCall.jl/dev/
https://lilithhafner.github.io/PythonCall.jl/stable/pythoncall-reference/#PythonCall.pybuiltins

https://lilithhafner.github.io
https://lilithhafner.github.io/Nonexistant.jl

One downside is that this breaks the documentation of all other packages using your github.io domain
https://lilithhafner.github.io/Minesweeper.jl/stable/

It won't be great for SEO, but tbh it's our responsibility to make good documentation and it's search engines' responsibility to make it discoverable.

To make this actually work, simply copy the contents of https://github.com/LilithHafner/lilithhafner.github.io to a new repository https://github.com/cjdoris/cjdoris.github.io and change "lilithhafner" to "cjdoris" on [this line](https://github.com/LilithHafner/lilithhafner.github.io/blob/86d49b2309b7f1f2a1c3a42fe60861b82e5a9fc9/404.html#L5)

**Comment by cjdoris** [comment]
Thanks for the suggestions, but I've just implemented a slightly less icky version by creating a bunch of pages which redirect to the corresponding page in the new location. They contain a canonical link, which search engines should notice and start to direct traffic there instead.

For example: https://github.com/cjdoris/cjdoris.github.io/blob/master/PythonCall.jl/stable/pythoncall/index.html

**Comment by LilithHafner** [comment]
You loose heading specifiers on the redirect, but not a big loss; I think you made the right choice.
