### ISSUE TITLE
[small nit]: gh repo link to docs is broken

### ISSUE THREAD

**Issue by tfiers** [JuliaPy/PythonCall.jl#371]
It's currently https://cjdoris.github.io/PythonCall.jl/stable, but that 404s.
Should now be https://juliapy.github.io/PythonCall.jl/stable/.

**Comment by KronosTheLate** [comment]
Came here to make this issue:
![image](https://github.com/JuliaPy/PythonCall.jl/assets/61620837/4edc6676-25e2-4fcd-ac17-f8717c3d3d70)

**Comment by cjdoris** [comment]
Fixed now, thanks!
