### ISSUE TITLE
conda-forge feedstock?

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaPy/PythonCall.jl#378]
Hi @cjdoris,

I'm eager to try porting [PySR](https://github.com/MilesCranmer/PySR) to PythonCall.jl from PyJulia. However, the last major hurdle is conda-forge support. Would it be possible to create a juliacall feedstock, similar to https://github.com/conda-forge/pyjulia-feedstock/? This would allow Python+Julia packages like PySR to depend on PythonCall in conda builds. (Similar to how other high-performance Python packages depend on a C++ backend)

For what it's worth, the conda-forge version of PySR has made up about 1/3rd of its total downloads while pip makes up 2/3rds. So I think conda, despite being slightly less popular, still captures a decent portion of Python users.

cc @mkitti 

Thanks!
Miles

**Comment by mkitti** [comment]
Did you want PythonCall.jl or juliacall in conda-forge?

**Comment by MilesCranmer** [comment]
juliacall (but it would have to package PythonCall.jl). I think it would have to depend on the julia-feedstock and use the Python that comes with the environment, rather than setting up its own CondaPkg.

**Comment by cjdoris** [comment]
There have been PRs around for adding JuliaPkg and JuliaCall to conda-forge for a while, but they seem to have stalled: https://github.com/conda-forge/staged-recipes/pull/20379, https://github.com/conda-forge/staged-recipes/pull/20380.

I don't have the time to contribute to the PRs myself (it's not simple) but you could team up with mkitti to get them through. I'm happy to provide opinions though.

**Comment by mkitti** [comment]
My main objections there was the name since conda-forge is supposed to be language agnostic. There is also an R package called juliacall, thus I think we should call the Python package pyjuliacall and the R package r-juliacall.

I will see about resubmitted those staged recipes with the naming scheme above.

**Comment by MilesCranmer** [comment]
Pinging this thread again. I should mention that I'm happy to maintain the feedstock once it's running. I just have no time to _set up_ the initial build due to teaching this term. Maybe that makes things a bit easier to push through. Once it's running I can maintain it, as I would presumably be able to switch away from PyJulia at that point, and can support PythonCall instead.

**Comment by MilesCranmer** [comment]
cc @schlichtanders too.

@cjdoris if you could help in getting the initial conda-forge working, I can take over maintaining it (and perhaps @mkitti as well). I can also help you long-term in maintaining PythonCall.jl/juliacall because I would depend on those for PySR. I've been good about keeping PyJulia working as it is my key dependency (https://github.com/JuliaPy/pyjulia/commits/master/). I am basically offering I could do the same for PythonCall.jl once it is ready for me.

I really just need your help in making the initial scheme work because it requires deep knowledge of the internals!

> I don't have the time to contribute to the PRs myself (it's not simple) but you could team up with mkitti to get them through. I'm happy to provide opinions though.

I can help with maintaining the ecosystem longer term, so if you can help now, I think would actually save net time.

**Comment by cjdoris** [comment]
Sure, what help do you need? The PR to add juliacall and juliapkg to conda-forge looks good to me.

Help maintaining PythonCall/JuliaCall is most welcome - my available time to spend on it fluctuates a lot over the year! I'm slowly working towards v1 but there's a lot to do.

**Comment by MilesCranmer** [comment]
Thanks! I think at this point, just helping get https://github.com/conda-forge/staged-recipes/pull/25097 pushed through as soon as possible would be best.

**Comment by mkitti** [comment]
Here's the prototype
```
conda install julialang::pyjuliacall
```

**Comment by MilesCranmer** [comment]
Thanks to @mkitti, this is all done!
