### ISSUE TITLE
support "dill" for serialization and deserialization

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/PythonCall.jl#424]
I am using PythonCall to define a Python interface from julia. It happens that I want to precompile Python code using Python's `compile` function and then send it to a remote process (Distributed).

Unfortunately the default `serialize_py` and `deserialize_py` use `pickle` which cannot handle code objects. 

**Describe the solution you'd like**
It would be perfect if PythonCall had an option to use `dill` instead of `pickle`

**Describe alternatives you've considered**
I am currently overwriting `serialize_py` and `deserialize_py` myself to use `"dill"`, and also add `"dill"` to the CondaPkg.toml.

**Comment by cjdoris** [comment]
Agreed this would be a nice feature.

**Comment by ma-sadeghi** [comment]
I think #454 is related, and will be automatically fixed if `dill` was an option.

**Comment by cjdoris** [comment]
This feature is merged to main - you can set `JULIA_PYTHONCALL_PICKLE=dill`.
