### ISSUE TITLE
Create conda pkg for juliacall at conda-forge

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPy/PythonCall.jl#425]
I am very surprised that PythonCall supports conda so well, but its python module `juliacall` itself is not available on conda (at least so far I couldn't find anything on [anaconda](https://anaconda.org/search?q=juliacall) or the installation documentation).

**Comment by cjdoris** [comment]
Indeed releasing on Conda Forge would be nice but I haven't had time to do so. Would be a welcome contribution.

**Comment by schlichtanders** [comment]
I was actively looking on julia dependent packages on Conda and actually currently it is a bit difficult to depend on conda julia or conda juliaup. Both don't have support for arm64 as of now.

My target architecture is mostly arm64, so I would wait for this to stabilize first. Or create a conda package without a julia dependency... also not ideal.

**Comment by MilesCranmer** [comment]
Also see https://github.com/JuliaPy/PythonCall.jl/issues/378#issuecomment-1755354797 for related PRs. Also very eager to see a conda-forge implemented for juliacall so I can move my libraries from pyjulia (but sadly no time to do this myself).

**Comment by MilesCranmer** [comment]
Now available as `conda-forge::pyjuliacall` FYI, feel free to close
