### ISSUE TITLE
Development version of juliacall starts the Julia REPL

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaPy/PythonCall.jl#447]
**Affects:** JuliaCall

1. Check out the current `main`.
2. Modify `pysrc/juliacall/juliapkg.json` to use the development version of PythonCall.

```diff
     "packages": {
         "PythonCall": {
             "uuid": "6099a3de-0909-46bc-b1f4-468b9a2dfc0d",
-            "version": "=0.9.15"
+            "path": "../..",
+            "dev": true
         }
     }
 }
```

4. Install `juliacall` locally with `pip install .` in the root of `PythonCall.jl`
5. Open IPython and try to import `juliacall`. This results in the Julia REPL itself opening:

![Screenshot 2024-01-28 at 10 36 48](https://github.com/JuliaPy/PythonCall.jl/assets/7593028/ef7c3712-a5cd-4dad-9b54-8927cb2549d4)

6.a. If I run `exit()` in the Julia REPL, both the Julia REPL and Python REPL quit....
6.b. If I use `ctrl-D` in the Julia REPL, I go back to the Python REPL and everything seems to be okay.

Any idea?

**Comment by cjdoris** [comment]
Oh yeah, this was a bug introduced by a recent refactor. I fixed it in a branch but not on main. Fixed on main now!
