### ISSUE TITLE
Using development version of package opens Julia REPL

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaPy/PythonCall.jl#451]
**Affects:** JuliaCall

**Describe the bug**

If I add a development dependency to my `juliapkg.json`, and then import my Python package, the Julia REPL will open. For example,  on the `pythoncall-try-3` branch of PySR, I modified `juliapkg.json` as follows:

```json
{
    "julia": "1.6",
    "packages": {
        "SymbolicRegression": {
            "uuid": "8254be44-1295-4e6a-a16d-46603ac705cb",
            "dev": true,
            "path": "../SymbolicRegression.jl"
        },
        "ClusterManagers": {
            "uuid": "34f1f09b-3a8b-5176-ab39-66d58a4d544e",
            "version": "0.4"
        }
    }
}
```

I then install PySR and do `import pysr`. This gives me the following:

![Screenshot 2024-02-07 at 14 28 52](https://github.com/JuliaPy/PythonCall.jl/assets/7593028/533a9192-7fa1-4f7b-a902-ed24bf4713d7)

I am able to exit the Julia REPL which returns me to the Python REPL.

I tried with the version of PythonCall.jl in `main` and I still see this issue.

**Comment by MilesCranmer** [comment]
@cjdoris Seems like the same thing also happens when specifying a particular revision of a Git repository.

**Comment by MilesCranmer** [comment]
Can a fix for this be back ported to 0.9?

**Comment by cjdoris** [comment]
The main branch is 0.9.

I thought I fixed this on main a while back. Can you check again? If seems really weird that it would only happen for dev packages. Maybe juliapkg is not getting the version of PythonCall you think it's getting?

**Comment by MilesCranmer** [comment]
I haven’t seen this issue ever since. It must have been an old package. Closing until it reappears..
