### ISSUE TITLE
use existing julia install

### ISSUE THREAD

**Issue by adienes** [JuliaPy/PythonCall.jl#489]
I am trying to install Julia + some packages in a a docker image, and run it in python with `juliacall`

there seems to be quite a lot of magic going on with automatically creating new environments, downloading packages, etc. etc.

I don't want _any_ of that. is there a way to ask juliacall to "just please use this julia environment" and go ahead and fail if there are any version incompatibilities etc. ?

**Comment by cjdoris** [comment]
Yep, check out the docs for juliapkg, which handles all that installation: https://github.com/JuliaPy/pyjuliapkg
