### ISSUE TITLE
OSError on Apple M2 Chip

### ISSUE THREAD

**Issue by dchung0741** [JuliaPy/PythonCall.jl#508]
**Describe the bug**
When installing `julacall` via `pip install juliacall` and run `import juliacall`,
I got 
```
OSError: dlopen(/Applications/Julia-1.8.app/Contents/Resources/julia/lib/libjulia.1.8.dylib, 0x000A): tried: '/Applications/Julia-
1.8.app/Contents/Resources/julia/lib/libjulia.1.8.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 
'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Julia-1.8.app/Contents/Resources/julia/lib/libjulia.1.8.dylib' (no 
such file), '/Applications/Julia-1.8.app/Contents/Resources/julia/lib/libjulia.1.8.dylib' (mach-o file, but is an incompatible architecture 
(have 'arm64', need 'x86_64'))
```

**My system**
- OS: Mac2023  with M2 chip
- julia version 1.8.5
- If an issue with JuliaCall, the output of `pip list` or `conda list` and `juliapkg.status()`:

|Package |           Version|
|:-------:|:--------------|
juliacall|             0.9.20
juliapkg|            0.1.13
numpy|             1.26.4
pip |                  24.0
scipy |              1.13.1
semver  |          3.0.2
setuptools |      69.5.1
typing_extensions | 4.12.1
wheel  |           0.43.0

I could run this a couple of months ago, but failed this week
Thank you!

**Comment by hameerabbasi** [comment]
It seems like you have an x86_64 version of Julia installed in `/Applications` but a arm64 version of Python. Both need to be the same to work in the same process.

**Comment by dchung0741** [comment]
Thanks for the reply. 
I think I somehow managed to resolve the issue.
The solution was to install rosetta an  the x86 version of Julia.
